import '../models/inventory_models.dart';
import '../models/stock_models.dart';

class MockRepository {
  static final List<InventoryItem> items = [
    const InventoryItem(
      id: '1',
      code: 'CH-001',
      name: 'Chicken Breast',
      category: 'Meat',
      unit: 'Kg',
      purchasePrice: 135.0,
      internalCost: 145.0,
      minStock: 20,
      maxStock: 120,
      description: 'Fresh boneless chicken for kitchen production.',
      stockOnHand: 48,
      reorderPoint: 24,
      status: 'Healthy',
    ),
    const InventoryItem(
      id: '2',
      code: 'RI-002',
      name: 'Basmati Rice',
      category: 'Dry Food',
      unit: 'Kg',
      purchasePrice: 95.0,
      internalCost: 105.0,
      minStock: 30,
      maxStock: 200,
      description: 'Premium rice for bulk meal service.',
      stockOnHand: 14,
      reorderPoint: 18,
      status: 'Low Stock',
    ),
    const InventoryItem(
      id: '3',
      code: 'DA-003',
      name: 'Milk Powder',
      category: 'Dairy',
      unit: 'Bag',
      purchasePrice: 420.0,
      internalCost: 450.0,
      minStock: 10,
      maxStock: 60,
      description: 'Used for desserts and beverage preparation.',
      stockOnHand: 63,
      reorderPoint: 10,
      status: 'Healthy',
    ),
  ];

  static final List<Supplier> suppliers = [
    const Supplier(
      id: 's1',
      name: 'Mulu Bekele',
      company: 'Fresh Foods PLC',
      contactPerson: 'Mulu Bekele',
      phone: '+251911223344',
      email: 'mulu@freshfoods.et',
      address: 'Addis Ababa',
      taxNumber: 'TAX-1001',
      status: 'Active',
      outstandingBalance: 12000,
    ),
    const Supplier(
      id: 's2',
      name: 'Daniel Tesfaye',
      company: 'Urban Pantry',
      contactPerson: 'Daniel Tesfaye',
      phone: '+251922334455',
      email: 'daniel@urbanpantry.et',
      address: 'Bole',
      taxNumber: 'TAX-2002',
      status: 'Pending',
      outstandingBalance: 6400,
    ),
  ];

  static final List<PurchaseRecord> purchases = [
    PurchaseRecord(
      id: 'p1',
      number: 'PO-1048',
      supplier: 'Fresh Foods PLC',
      date: DateTime(2026, 7, 22),
      item: 'Chicken Breast',
      quantity: 40,
      unitPrice: 135,
      vat: 1080,
      discount: 200,
      total: 5400,
    ),
    PurchaseRecord(
      id: 'p2',
      number: 'PO-1049',
      supplier: 'Urban Pantry',
      date: DateTime(2026, 7, 23),
      item: 'Basmati Rice',
      quantity: 25,
      unitPrice: 95,
      vat: 712.5,
      discount: 0,
      total: 2375,
    ),
  ];

  static final List<StockMovement> movements = [
    StockMovement(
      id: 'm1',
      item: 'Chicken Breast',
      type: 'Purchase',
      quantity: 40,
      date: DateTime(2026, 7, 22),
      note: 'Received purchase order PO-1048',
    ),
    StockMovement(
      id: 'm2',
      item: 'Basmati Rice',
      type: 'Kitchen Issue',
      quantity: 8,
      date: DateTime(2026, 7, 24),
      note: 'Issued to kitchen for buffet service',
    ),
    StockMovement(
      id: 'm3',
      item: 'Milk Powder',
      type: 'Waste',
      quantity: 2,
      date: DateTime(2026, 7, 20),
      note: 'Damaged packaging',
    ),
  ];

  static final List<Recipe> recipes = [
    const Recipe(
      id: 'r1',
      name: 'Chicken Curry',
      description: 'Signature catering chicken curry with fresh spices.',
      ingredients: ['Chicken — 2 Kg', 'Onion — 1 Kg', 'Tomato — 0.5 Kg', 'Oil — 0.25 L', 'Salt — 0.05 Kg'],
      foodCost: 480.0,
    ),
    const Recipe(
      id: 'r2',
      name: 'Vegetable Pilaf',
      description: 'Mixed rice dish with fresh vegetables.',
      ingredients: ['Rice — 1.5 Kg', 'Carrot — 0.4 Kg', 'Peas — 0.3 Kg', 'Oil — 0.1 L'],
      foodCost: 220.0,
    ),
  ];

  static final List<AlertItem> alerts = [
    AlertItem(
      id: 'a1',
      title: 'Low stock alert',
      detail: 'Basmati Rice is below reorder level.',
      date: DateTime(2026, 7, 24),
      severity: 'High',
    ),
    AlertItem(
      id: 'a2',
      title: 'Expiry upcoming',
      detail: 'Milk Powder expires in 3 days.',
      date: DateTime(2026, 7, 24),
      severity: 'Medium',
    ),
  ];

  static final List<RecipeItem> recipeItems = [
    RecipeItem(
      id: 'ri1',
      name: 'Chicken Curry',
      category: 'Main Course',
      description: 'Signature catering chicken curry with fresh spices and aromatic herbs.',
      servings: 10,
      prepTime: '45 min',
      sellingPrice: 850.0,
      status: 'Active',
      ingredients: const [
        RecipeIngredient(name: 'Chicken Breast', quantity: 2.0, unit: 'Kg', unitCost: 135.0),
        RecipeIngredient(name: 'Onion', quantity: 1.0, unit: 'Kg', unitCost: 25.0),
        RecipeIngredient(name: 'Tomato', quantity: 0.5, unit: 'Kg', unitCost: 20.0),
        RecipeIngredient(name: 'Cooking Oil', quantity: 0.25, unit: 'L', unitCost: 60.0),
        RecipeIngredient(name: 'Mixed Spices', quantity: 0.05, unit: 'Kg', unitCost: 200.0),
      ],
    ),
    RecipeItem(
      id: 'ri2',
      name: 'Vegetable Pilaf',
      category: 'Main Course',
      description: 'Mixed rice dish with seasonal fresh vegetables and aromatic spices.',
      servings: 8,
      prepTime: '35 min',
      sellingPrice: 560.0,
      status: 'Active',
      ingredients: const [
        RecipeIngredient(name: 'Basmati Rice', quantity: 1.5, unit: 'Kg', unitCost: 95.0),
        RecipeIngredient(name: 'Carrot', quantity: 0.4, unit: 'Kg', unitCost: 18.0),
        RecipeIngredient(name: 'Green Peas', quantity: 0.3, unit: 'Kg', unitCost: 35.0),
        RecipeIngredient(name: 'Cooking Oil', quantity: 0.1, unit: 'L', unitCost: 60.0),
      ],
    ),
    RecipeItem(
      id: 'ri3',
      name: 'Milk Pudding',
      category: 'Dessert',
      description: 'Creamy dessert made with milk powder, sugar and vanilla essence.',
      servings: 12,
      prepTime: '20 min',
      sellingPrice: 480.0,
      status: 'Active',
      ingredients: const [
        RecipeIngredient(name: 'Milk Powder', quantity: 0.8, unit: 'Kg', unitCost: 420.0),
        RecipeIngredient(name: 'Sugar', quantity: 0.3, unit: 'Kg', unitCost: 45.0),
        RecipeIngredient(name: 'Vanilla Essence', quantity: 0.02, unit: 'L', unitCost: 300.0),
      ],
    ),
    RecipeItem(
      id: 'ri4',
      name: 'Beef Tibs',
      category: 'Main Course',
      description: 'Ethiopian-style sautéed beef with peppers, onions and spiced butter.',
      servings: 8,
      prepTime: '30 min',
      sellingPrice: 1100.0,
      status: 'Active',
      ingredients: const [
        RecipeIngredient(name: 'Beef Sirloin', quantity: 2.5, unit: 'Kg', unitCost: 280.0),
        RecipeIngredient(name: 'Onion', quantity: 0.8, unit: 'Kg', unitCost: 25.0),
        RecipeIngredient(name: 'Green Pepper', quantity: 0.4, unit: 'Kg', unitCost: 30.0),
        RecipeIngredient(name: 'Spiced Butter', quantity: 0.15, unit: 'Kg', unitCost: 180.0),
      ],
    ),
    RecipeItem(
      id: 'ri5',
      name: 'Fresh Juice Blend',
      category: 'Beverage',
      description: 'Mixed seasonal fruit juice blend served at catering events.',
      servings: 20,
      prepTime: '10 min',
      sellingPrice: 320.0,
      status: 'Inactive',
      ingredients: const [
        RecipeIngredient(name: 'Mango', quantity: 1.5, unit: 'Kg', unitCost: 40.0),
        RecipeIngredient(name: 'Papaya', quantity: 1.0, unit: 'Kg', unitCost: 30.0),
        RecipeIngredient(name: 'Sugar', quantity: 0.2, unit: 'Kg', unitCost: 45.0),
      ],
    ),
  ];

  static final List<WasteRecord> wasteRecords = [
    WasteRecord(
      id: 'w1',
      number: 'WS-3001',
      item: 'Chicken Breast',
      category: 'Meat',
      unit: 'Kg',
      quantity: 2.5,
      estimatedCost: 337.5,
      reason: 'Spoilage',
      recordedBy: 'Selam K.',
      date: DateTime(2026, 7, 24),
      status: 'Confirmed',
      notes: 'Left outside cold storage overnight. Disposed of safely.',
    ),
    WasteRecord(
      id: 'w2',
      number: 'WS-3002',
      item: 'Milk Powder',
      category: 'Dairy',
      unit: 'Kg',
      quantity: 1.0,
      estimatedCost: 420.0,
      reason: 'Damaged Packaging',
      recordedBy: 'Alemu B.',
      date: DateTime(2026, 7, 22),
      status: 'Confirmed',
      notes: 'Torn bag during unloading. Contents contaminated.',
    ),
    WasteRecord(
      id: 'w3',
      number: 'WS-3003',
      item: 'Basmati Rice',
      category: 'Dry Food',
      unit: 'Kg',
      quantity: 3.0,
      estimatedCost: 285.0,
      reason: 'Cooking Overproduction',
      recordedBy: 'Mekdes H.',
      date: DateTime(2026, 7, 20),
      status: 'Pending Review',
      notes: 'Over-cooked batch from banquet. Could not be reused.',
    ),
    WasteRecord(
      id: 'w4',
      number: 'WS-3004',
      item: 'Cooking Oil',
      category: 'Oil',
      unit: 'L',
      quantity: 4.0,
      estimatedCost: 240.0,
      reason: 'Expired',
      recordedBy: 'Dawit T.',
      date: DateTime(2026, 7, 18),
      status: 'Confirmed',
      notes: 'Past best-before date. Disposed of per health guidelines.',
    ),
    WasteRecord(
      id: 'w5',
      number: 'WS-3005',
      item: 'Tomatoes',
      category: 'Vegetables',
      unit: 'Kg',
      quantity: 5.0,
      estimatedCost: 100.0,
      reason: 'Over-ripened',
      recordedBy: 'Netsanet Y.',
      date: DateTime(2026, 7, 15),
      status: 'Confirmed',
      notes: 'Not used within shelf life. Composted on-site.',
    ),
  ];

  static final List<ExpiryItem> expiryItems = [
    ExpiryItem(
      id: 'e1',
      item: 'Milk Powder',
      category: 'Dairy',
      unit: 'Kg',
      quantity: 12.0,
      expiryDate: DateTime(2026, 8, 6),
      batchNumber: 'BT-4401',
      location: 'Main Store – Shelf B2',
      status: 'Expiring Soon',
    ),
    ExpiryItem(
      id: 'e2',
      item: 'Cooking Oil',
      category: 'Oil',
      unit: 'L',
      quantity: 8.5,
      expiryDate: DateTime(2026, 7, 30),
      batchNumber: 'BT-4210',
      location: 'Main Store – Shelf A4',
      status: 'Expired',
    ),
    ExpiryItem(
      id: 'e3',
      item: 'Tomato Paste',
      category: 'Canned Goods',
      unit: 'Kg',
      quantity: 6.0,
      expiryDate: DateTime(2026, 8, 10),
      batchNumber: 'BT-4512',
      location: 'Branch 2 – Shelf C1',
      status: 'Expiring Soon',
    ),
    ExpiryItem(
      id: 'e4',
      item: 'Vanilla Essence',
      category: 'Spices',
      unit: 'L',
      quantity: 0.5,
      expiryDate: DateTime(2026, 7, 28),
      batchNumber: 'BT-4090',
      location: 'Main Store – Shelf D3',
      status: 'Expired',
    ),
    ExpiryItem(
      id: 'e5',
      item: 'Beef Sirloin',
      category: 'Meat',
      unit: 'Kg',
      quantity: 15.0,
      expiryDate: DateTime(2026, 8, 20),
      batchNumber: 'BT-4630',
      location: 'Cold Room – Section 1',
      status: 'OK',
    ),
    ExpiryItem(
      id: 'e6',
      item: 'Basmati Rice',
      category: 'Dry Food',
      unit: 'Kg',
      quantity: 50.0,
      expiryDate: DateTime(2027, 1, 15),
      batchNumber: 'BT-4701',
      location: 'Main Store – Shelf A1',
      status: 'OK',
    ),
    ExpiryItem(
      id: 'e7',
      item: 'Yoghurt',
      category: 'Dairy',
      unit: 'Kg',
      quantity: 4.0,
      expiryDate: DateTime(2026, 8, 7),
      batchNumber: 'BT-4455',
      location: 'Cold Room – Section 2',
      status: 'Expiring Soon',
    ),
  ];

  static final List<AppUser> appUsers = [
    AppUser(
      id: 'u1',
      name: 'Robel Tadesse',
      email: 'robel@cateringcontrol.et',
      phone: '+251911001122',
      role: 'Admin',
      department: 'Management',
      status: 'Active',
      createdAt: DateTime(2025, 1, 10),
      lastLogin: '24 Jul 2026, 08:42',
      permissions: ['inventory', 'suppliers', 'purchases', 'recipes', 'waste', 'expiry', 'users', 'reports'],
    ),
    AppUser(
      id: 'u2',
      name: 'Selam Kebede',
      email: 'selam@cateringcontrol.et',
      phone: '+251922334455',
      role: 'Store Manager',
      department: 'Main Store',
      status: 'Active',
      createdAt: DateTime(2025, 3, 5),
      lastLogin: '24 Jul 2026, 09:15',
      permissions: ['inventory', 'suppliers', 'purchases', 'waste', 'expiry'],
    ),
    AppUser(
      id: 'u3',
      name: 'Alemu Bekele',
      email: 'alemu@cateringcontrol.et',
      phone: '+251933445566',
      role: 'Kitchen Supervisor',
      department: 'Main Kitchen',
      status: 'Active',
      createdAt: DateTime(2025, 4, 18),
      lastLogin: '23 Jul 2026, 16:30',
      permissions: ['inventory', 'recipes', 'waste'],
    ),
    AppUser(
      id: 'u4',
      name: 'Mekdes Hailu',
      email: 'mekdes@cateringcontrol.et',
      phone: '+251944556677',
      role: 'Cashier',
      department: 'Finance',
      status: 'Active',
      createdAt: DateTime(2025, 6, 22),
      lastLogin: '22 Jul 2026, 11:00',
      permissions: ['purchases', 'reports'],
    ),
    AppUser(
      id: 'u5',
      name: 'Dawit Tesfaye',
      email: 'dawit@cateringcontrol.et',
      phone: '+251955667788',
      role: 'Storekeeper',
      department: 'Branch 2 Store',
      status: 'Inactive',
      createdAt: DateTime(2025, 7, 14),
      lastLogin: '10 Jun 2026, 14:20',
      permissions: ['inventory', 'waste', 'expiry'],
    ),
    AppUser(
      id: 'u6',
      name: 'Netsanet Yohannes',
      email: 'netsanet@cateringcontrol.et',
      phone: '+251966778899',
      role: 'Chef',
      department: 'Prep Kitchen',
      status: 'Active',
      createdAt: DateTime(2025, 9, 3),
      lastLogin: '24 Jul 2026, 07:55',
      permissions: ['recipes', 'waste'],
    ),
  ];

  // ── Food Stock ────────────────────────────────────────────────────────────
  static final List<FoodStockItem> foodStock = [
    FoodStockItem(
      id: 'fs1', code: 'FS-001', name: 'Chicken Breast',
      category: 'Meat', unit: 'Kg', purchasePrice: 135.0,
      quantity: 48.0, minQuantity: 20, maxQuantity: 120,
      location: 'Cold Room – Section 1', supplier: 'Fresh Foods PLC',
      status: 'Healthy', batchNumber: 'BT-CH01',
      description: 'Fresh boneless chicken for kitchen production.',
      lastUpdated: DateTime(2026, 7, 24),
      expiryDate: DateTime(2026, 8, 5),
      requiresRefrigeration: true,
    ),
    FoodStockItem(
      id: 'fs2', code: 'FS-002', name: 'Basmati Rice',
      category: 'Dry Food', unit: 'Kg', purchasePrice: 95.0,
      quantity: 14.0, minQuantity: 30, maxQuantity: 200,
      location: 'Main Store – Shelf A1', supplier: 'Urban Pantry',
      status: 'Low Stock', batchNumber: 'BT-RI02',
      description: 'Premium rice for bulk meal service.',
      lastUpdated: DateTime(2026, 7, 23),
      expiryDate: DateTime(2027, 1, 15),
    ),
    FoodStockItem(
      id: 'fs3', code: 'FS-003', name: 'Cooking Oil',
      category: 'Oil', unit: 'L', purchasePrice: 60.0,
      quantity: 32.0, minQuantity: 10, maxQuantity: 80,
      location: 'Main Store – Shelf A4', supplier: 'Urban Pantry',
      status: 'Healthy', batchNumber: 'BT-OL03',
      description: 'Refined sunflower oil for frying and sautéing.',
      lastUpdated: DateTime(2026, 7, 20),
      expiryDate: DateTime(2026, 9, 1),
    ),
    FoodStockItem(
      id: 'fs4', code: 'FS-004', name: 'Milk Powder',
      category: 'Dairy', unit: 'Kg', purchasePrice: 420.0,
      quantity: 12.0, minQuantity: 10, maxQuantity: 60,
      location: 'Main Store – Shelf B2', supplier: 'Fresh Foods PLC',
      status: 'Healthy', batchNumber: 'BT-4401',
      description: 'Used for desserts and beverage preparation.',
      lastUpdated: DateTime(2026, 7, 22),
      expiryDate: DateTime(2026, 8, 6),
    ),
    FoodStockItem(
      id: 'fs5', code: 'FS-005', name: 'Tomatoes',
      category: 'Vegetables', unit: 'Kg', purchasePrice: 20.0,
      quantity: 25.0, minQuantity: 15, maxQuantity: 60,
      location: 'Cold Room – Section 2', supplier: 'Fresh Foods PLC',
      status: 'Healthy', batchNumber: 'BT-TM05',
      description: 'Fresh tomatoes for sauces and salads.',
      lastUpdated: DateTime(2026, 7, 24),
      expiryDate: DateTime(2026, 8, 3),
      requiresRefrigeration: true,
    ),
    FoodStockItem(
      id: 'fs6', code: 'FS-006', name: 'Onions',
      category: 'Vegetables', unit: 'Kg', purchasePrice: 25.0,
      quantity: 40.0, minQuantity: 20, maxQuantity: 100,
      location: 'Main Store – Shelf C3', supplier: 'Fresh Foods PLC',
      status: 'Healthy', batchNumber: 'BT-ON06',
      description: 'Red onions for cooking and garnish.',
      lastUpdated: DateTime(2026, 7, 21),
      expiryDate: DateTime(2026, 9, 15),
    ),
  ];

  // ── Catering Stock ────────────────────────────────────────────────────────
  static final List<CateringStockItem> cateringStock = [
    // Permanent – reusable assets
    CateringStockItem(
      id: 'cs1', code: 'CP-001', name: 'Round Banquet Table',
      category: 'Tables', unit: 'Pcs', purchasePrice: 2800.0,
      quantity: 24, minQuantity: 10, maxQuantity: 40,
      location: 'Equipment Store', supplier: 'Event Solutions PLC',
      status: 'Healthy', subtype: CateringSubtype.permanent,
      description: '5 ft round banquet table, foldable legs.',
      lastUpdated: DateTime(2026, 7, 10),
      condition: 'Good', isReserved: true, reservedFor: 'Gala Dinner – Aug 8',
    ),
    CateringStockItem(
      id: 'cs2', code: 'CP-002', name: 'Banquet Chair',
      category: 'Chairs', unit: 'Pcs', purchasePrice: 650.0,
      quantity: 180, minQuantity: 50, maxQuantity: 300,
      location: 'Equipment Store', supplier: 'Event Solutions PLC',
      status: 'Healthy', subtype: CateringSubtype.permanent,
      description: 'Padded banquet chairs with steel frame.',
      lastUpdated: DateTime(2026, 7, 10),
      condition: 'Good', isReserved: false,
    ),
    CateringStockItem(
      id: 'cs3', code: 'CP-003', name: 'Chafing Dish (Full)',
      category: 'Serving Equipment', unit: 'Pcs', purchasePrice: 1200.0,
      quantity: 18, minQuantity: 8, maxQuantity: 30,
      location: 'Equipment Store', supplier: 'Catering Depot',
      status: 'Healthy', subtype: CateringSubtype.permanent,
      description: 'Full-size stainless steel chafing dish with lid.',
      lastUpdated: DateTime(2026, 7, 15),
      condition: 'Good', isReserved: false,
    ),
    CateringStockItem(
      id: 'cs4', code: 'CP-004', name: 'Buffet Tray (Stainless)',
      category: 'Serving Equipment', unit: 'Pcs', purchasePrice: 380.0,
      quantity: 6, minQuantity: 10, maxQuantity: 40,
      location: 'Equipment Store', supplier: 'Catering Depot',
      status: 'Low Stock', subtype: CateringSubtype.permanent,
      description: 'Large stainless steel buffet serving tray.',
      lastUpdated: DateTime(2026, 7, 18),
      condition: 'Fair', isReserved: false,
    ),
    // Temporary – consumables
    CateringStockItem(
      id: 'ct1', code: 'CT-001', name: 'Disposable Plates (10")',
      category: 'Disposables', unit: 'Pack', purchasePrice: 85.0,
      quantity: 120, minQuantity: 40, maxQuantity: 300,
      location: 'Consumables Store', supplier: 'Pack & Go Ltd',
      status: 'Healthy', subtype: CateringSubtype.temporary,
      description: '50-piece packs of 10-inch disposable plates.',
      lastUpdated: DateTime(2026, 7, 22),
      packSize: 50, consumptionRate: '2 packs/event',
    ),
    CateringStockItem(
      id: 'ct2', code: 'CT-002', name: 'Disposable Cups (250ml)',
      category: 'Disposables', unit: 'Pack', purchasePrice: 45.0,
      quantity: 80, minQuantity: 30, maxQuantity: 200,
      location: 'Consumables Store', supplier: 'Pack & Go Ltd',
      status: 'Healthy', subtype: CateringSubtype.temporary,
      description: '100-piece packs of 250ml clear plastic cups.',
      lastUpdated: DateTime(2026, 7, 22),
      packSize: 100, consumptionRate: '3 packs/event',
    ),
    CateringStockItem(
      id: 'ct3', code: 'CT-003', name: 'Paper Napkins',
      category: 'Disposables', unit: 'Pack', purchasePrice: 30.0,
      quantity: 18, minQuantity: 20, maxQuantity: 100,
      location: 'Consumables Store', supplier: 'Pack & Go Ltd',
      status: 'Low Stock', subtype: CateringSubtype.temporary,
      description: '200-sheet packs of white 2-ply napkins.',
      lastUpdated: DateTime(2026, 7, 20),
      packSize: 200, consumptionRate: '4 packs/event',
    ),
    CateringStockItem(
      id: 'ct4', code: 'CT-004', name: 'Food Containers (1L)',
      category: 'Packaging', unit: 'Pcs', purchasePrice: 12.0,
      quantity: 350, minQuantity: 100, maxQuantity: 600,
      location: 'Consumables Store', supplier: 'Pack & Go Ltd',
      status: 'Healthy', subtype: CateringSubtype.temporary,
      description: '1-litre airtight food-safe containers for takeaway.',
      lastUpdated: DateTime(2026, 7, 19),
      packSize: 1, consumptionRate: '50 pcs/event',
    ),
  ];

  // ── Electronics Stock ──────────────────────────────────────────────────────
  static final List<ElectronicsStockItem> electronicsStock = [
    ElectronicsStockItem(
      id: 'el1', code: 'EL-001', name: 'Point-of-Sale Terminal',
      category: 'POS Systems', unit: 'Pcs', purchasePrice: 18500.0,
      quantity: 3, minQuantity: 1, maxQuantity: 6,
      location: 'IT Room – Cabinet A', supplier: 'TechZone Ethiopia',
      status: 'Healthy', brand: 'Sunmi', model: 'T2 Mini',
      serialNumber: 'SN-TZ-001', assetTag: 'AT-EL-001',
      maintenanceStatus: 'OK',
      description: 'Android-based all-in-one POS terminal.',
      lastUpdated: DateTime(2026, 6, 1),
      warrantyExpiry: DateTime(2028, 6, 1),
      lastMaintenanceDate: DateTime(2026, 4, 10),
    ),
    ElectronicsStockItem(
      id: 'el2', code: 'EL-002', name: 'Barcode Scanner',
      category: 'Scanners', unit: 'Pcs', purchasePrice: 3200.0,
      quantity: 5, minQuantity: 2, maxQuantity: 10,
      location: 'Main Store – Cabinet B', supplier: 'TechZone Ethiopia',
      status: 'Healthy', brand: 'Honeywell', model: 'Voyager 1250g',
      serialNumber: 'SN-BC-002', assetTag: 'AT-EL-002',
      maintenanceStatus: 'OK',
      description: 'USB barcode scanner for inventory management.',
      lastUpdated: DateTime(2026, 5, 15),
      warrantyExpiry: DateTime(2027, 5, 15),
      lastMaintenanceDate: DateTime(2026, 3, 20),
    ),
    ElectronicsStockItem(
      id: 'el3', code: 'EL-003', name: 'Label Printer',
      category: 'Printers', unit: 'Pcs', purchasePrice: 7800.0,
      quantity: 2, minQuantity: 1, maxQuantity: 4,
      location: 'Main Store – Cabinet B', supplier: 'TechZone Ethiopia',
      status: 'Healthy', brand: 'Zebra', model: 'ZD421',
      serialNumber: 'SN-LP-003', assetTag: 'AT-EL-003',
      maintenanceStatus: 'Due',
      description: 'Thermal label printer for barcode and QR labels.',
      lastUpdated: DateTime(2026, 7, 1),
      warrantyExpiry: DateTime(2027, 12, 1),
      lastMaintenanceDate: DateTime(2026, 1, 5),
    ),
    ElectronicsStockItem(
      id: 'el4', code: 'EL-004', name: 'Commercial Refrigerator',
      category: 'Cold Equipment', unit: 'Pcs', purchasePrice: 62000.0,
      quantity: 2, minQuantity: 1, maxQuantity: 4,
      location: 'Cold Room – North Wall', supplier: 'Cool Tech PLC',
      status: 'Healthy', brand: 'Samsung', model: 'RR39A7463WT',
      serialNumber: 'SN-RF-004', assetTag: 'AT-EL-004',
      maintenanceStatus: 'OK',
      description: '390L upright commercial refrigerator.',
      lastUpdated: DateTime(2026, 7, 5),
      warrantyExpiry: DateTime(2029, 7, 5),
      lastMaintenanceDate: DateTime(2026, 6, 10),
    ),
  ];

  // ── Stock Movement History ────────────────────────────────────────────────
  static final List<StockMovementEntry> stockMovements = [
    StockMovementEntry(
      id: 'sm1', stockItemId: 'fs1', type: 'Stock In',
      quantity: 40, unit: 'Kg', performedBy: 'Selam K.',
      date: DateTime(2026, 7, 22),
      note: 'Received PO-1048 from Fresh Foods PLC',
    ),
    StockMovementEntry(
      id: 'sm2', stockItemId: 'fs2', type: 'Stock Out',
      quantity: 8, unit: 'Kg', performedBy: 'Alemu B.',
      date: DateTime(2026, 7, 24),
      note: 'Issued to kitchen for buffet service',
    ),
    StockMovementEntry(
      id: 'sm3', stockItemId: 'cs1', type: 'Transfer',
      quantity: 10, unit: 'Pcs', performedBy: 'Robel T.',
      date: DateTime(2026, 7, 20),
      note: 'Transferred to Branch 2 for weekend event',
    ),
    StockMovementEntry(
      id: 'sm4', stockItemId: 'el3', type: 'Adjustment',
      quantity: 1, unit: 'Pcs', performedBy: 'Robel T.',
      date: DateTime(2026, 7, 18),
      note: 'Physical count reconciliation',
    ),
    StockMovementEntry(
      id: 'sm5', stockItemId: 'ct3', type: 'Stock Out',
      quantity: 5, unit: 'Pack', performedBy: 'Netsanet Y.',
      date: DateTime(2026, 7, 23),
      note: 'Used for corporate lunch event',
    ),
    StockMovementEntry(
      id: 'sm6', stockItemId: 'cs2', type: 'Return',
      quantity: 20, unit: 'Pcs', performedBy: 'Mekdes H.',
      date: DateTime(2026, 7, 25),
      note: 'Returned from Hilton event – chairs in good condition',
    ),
  ];
}